# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1235, 612)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(6, 50, 1211, 521))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTabWidget:tab-bar\n"
"{\n"
"alignment: center;\n"
"}\n"
"\n"
"QTabBar:tab\n"
"{\n"
"\n"
"width:500px;\n"
"height:40px;\n"
"border:1px solid rgb(120,120,120);\n"
"}\n"
"\n"
"QTabBar:tab::selected\n"
"{\n"
"    background-color: rgb(120, 120, 120);\n"
"color:rgb(0,255,0);\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar:tab:!selected\n"
"{\n"
"color:rgb(255,0,0)\n"
"}\n"
"\n"
"QTabBar:tab:!selected:hover\n"
"{\n"
"    background-color: rgb(255, 0, 0);\n"
"color:rgb(255,255,255)\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.line = QtWidgets.QFrame(parent=self.widget)
        self.line.setGeometry(QtCore.QRect(590, 0, 20, 451))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setStrikeOut(False)
        self.line.setFont(font)
        self.line.setStyleSheet("")
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setObjectName("line")
        self.tabWidget_2 = QtWidgets.QTabWidget(parent=self.widget)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 10, 561, 421))
        self.tabWidget_2.setStyleSheet("\n"
"\n"
"QTabWidget\n"
"{\n"
" background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QTabWidget:tab-bar\n"
"{\n"
"alignment: center;\n"
"}\n"
"\n"
"QTabBar:tab\n"
"{\n"
"\n"
"width:200px;\n"
"height:30px;\n"
"border:1px solid rgb(120,120,120);\n"
"}\n"
"\n"
"QTabBar:tab::selected\n"
"{\n"
"    background-color: rgb(160 ,160, 160);\n"
"color:rgb(0,255,0)\n"
"}\n"
"\n"
"\n"
"QTabBar:tab:!selected\n"
"{\n"
"color:rgb(255,0,0)\n"
"}\n"
"\n"
"QTabBar:tab:!selected:hover\n"
"{\n"
"    background-color: rgb(255, 0, 0);\n"
"color:rgb(255,255,255)\n"
"}\n"
"\n"
"\n"
"QLineEdit {\n"
"width: 100px;\n"
"height:30px;\n"
"border: 1px solid rgb(0,0,0);\n"
"border-radius:50px;\n"
"\n"
"}\n"
"")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.widget1 = QtWidgets.QWidget()
        self.widget1.setObjectName("widget1")
        self.line_2 = QtWidgets.QFrame(parent=self.widget1)
        self.line_2.setGeometry(QtCore.QRect(170, 230, 118, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget = QtWidgets.QWidget(parent=self.widget1)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 260, 511, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_13 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_2.addWidget(self.lineEdit_13, 2, 1, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 2, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 1, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 0, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 0, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 1, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.widget1)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 40, 511, 171))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_1 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.lineEdit_1.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout.addWidget(self.lineEdit_1, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 2, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 2, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 3, 0, 1, 2)
        self.label_26 = QtWidgets.QLabel(parent=self.widget1)
        self.label_26.setGeometry(QtCore.QRect(40, 10, 131, 16))
        self.label_26.setStyleSheet("font: 600 16pt \"Bahnschrift SemiBold\";")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(parent=self.widget1)
        self.label_27.setGeometry(QtCore.QRect(40, 230, 131, 16))
        self.label_27.setStyleSheet("font: 600 16pt \"Bahnschrift SemiBold\";")
        self.label_27.setObjectName("label_27")
        self.tabWidget_2.addTab(self.widget1, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.tab_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 30, 511, 311))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_16 = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_3.addWidget(self.lineEdit_16, 0, 0, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_3.addWidget(self.lineEdit_22, 4, 0, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.lineEdit_23.setText("")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_3.addWidget(self.lineEdit_23, 4, 1, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_3.addWidget(self.lineEdit_17, 0, 1, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_3.addWidget(self.lineEdit_20, 3, 0, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_3.addWidget(self.lineEdit_18, 1, 0, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_3.addWidget(self.lineEdit_21, 3, 1, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.lineEdit_19.setText("")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_3.addWidget(self.lineEdit_19, 1, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setGeometry(QtCore.QRect(670, 390, 181, 31))
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"border:1px solid rgb(255,0,0);\n"
"background-color:rgb(255,255,255);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:!selected\n"
"{\n"
"color:rgb(255,0,0);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color:rgb(255,0,0);\n"
"color:rgb(255,255,255)\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:!enabled\n"
"{\n"
"border:1px solid rgb(120,120,120);\n"
"background-color:rgb(255,255,255);\n"
"color:rgb(120,120,120);\n"
"border-radius:15px;\n"
"\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_result = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_result.setGeometry(QtCore.QRect(860, 390, 291, 31))
        self.lineEdit_result.setStyleSheet("QLineEdit {\n"
"width: 100px;\n"
"height:30px;\n"
"border: 1px solid rgb(0,0,0);\n"
"border-radius:50px;\n"
"\n"
"}")
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(670, 10, 481, 361))
        self.label.setStyleSheet("\n"
"background-image: url(:/newPrefix/1.jpg);\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(1110, 90, 31, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(780, 300, 31, 41))
        self.label_3.setObjectName("label_3")
        self.label_28 = QtWidgets.QLabel(parent=self.widget)
        self.label_28.setGeometry(QtCore.QRect(690, 260, 31, 41))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(parent=self.widget)
        self.label_29.setGeometry(QtCore.QRect(690, 10, 31, 41))
        self.label_29.setObjectName("label_29")
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_3 = QtWidgets.QTabWidget(parent=self.tab_2)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 10, 1191, 471))
        self.tabWidget_3.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.tabWidget_3.setStyleSheet("\n"
"\n"
"QTabWidget\n"
"{\n"
"background-color: yellow;\n"
"}\n"
"\n"
"QTabWidget:tab-bar\n"
"{\n"
"alignment: center;\n"
"}\n"
"\n"
"QTabBar:tab\n"
"{\n"
"\n"
"width:300px;\n"
"height:30px;\n"
"}\n"
"\n"
"QTabBar:tab::selected\n"
"{\n"
"    background-color: rgb(160 ,160, 160);\n"
"color:rgb(0,255,0)\n"
"}\n"
"\n"
"\n"
"QTabBar:tab:!selected\n"
"{\n"
"color:rgb(255,0,0)\n"
"}\n"
"\n"
"QTabBar:tab:!selected:hover\n"
"{\n"
"    background-color: rgb(255, 0, 0);\n"
"color:rgb(255,255,255)\n"
"}\n"
"\n"
"\n"
"QLineEdit {\n"
"width: 100px;\n"
"height:30px;\n"
"border: 1px solid rgb(0,0,0);\n"
"border-radius:50px;\n"
"\n"
"}\n"
"")
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.line_3 = QtWidgets.QFrame(parent=self.tab)
        self.line_3.setGeometry(QtCore.QRect(400, 20, 16, 381))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 30, 361, 31))
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
"border:1px solid rgb(255,0,0);\n"
"background-color:rgb(255,255,255);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:!selected\n"
"{\n"
"color:rgb(255,0,0);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color:rgb(255,0,0);\n"
"color:rgb(255,255,255)\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:!enabled\n"
"{\n"
"border:1px solid rgb(120,120,120);\n"
"background-color:rgb(255,255,255);\n"
"color:rgb(120,120,120);\n"
"border-radius:15px;\n"
"\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 76, 371, 261))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidget_4 = QtWidgets.QTabWidget(parent=self.tab)
        self.tabWidget_4.setGeometry(QtCore.QRect(430, 30, 751, 401))
        self.tabWidget_4.setStyleSheet("QTabBar:tab\n"
"{\n"
"\n"
"width:200px;\n"
"height:30px;\n"
"border:1px solid rgb(120,120,120);\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:disabled\n"
"{\n"
"background-color: rgb(195, 195, 195);\n"
"color: rgb(255, 255, 255);\n"
"width:200px;\n"
"height:30px;\n"
"border:1px solid rgb(120,120,120);\n"
"}")
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.radioButton_1 = QtWidgets.QRadioButton(parent=self.tab_12)
        self.radioButton_1.setGeometry(QtCore.QRect(310, 200, 171, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.radioButton_1.setFont(font)
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.tab_12)
        self.radioButton_2.setGeometry(QtCore.QRect(310, 240, 171, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_25 = QtWidgets.QLabel(parent=self.tab_12)
        self.label_25.setGeometry(QtCore.QRect(30, 20, 691, 161))
        self.label_25.setObjectName("label_25")
        self.tabWidget_4.addTab(self.tab_12, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_15 = QtWidgets.QLabel(parent=self.tab_10)
        self.label_15.setGeometry(QtCore.QRect(470, 20, 131, 16))
        self.label_15.setStyleSheet("font: 600 16pt \"Bahnschrift SemiBold\";")
        self.label_15.setObjectName("label_15")
        self.layoutWidget3 = QtWidgets.QWidget(parent=self.tab_10)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 50, 301, 281))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_19 = QtWidgets.QLabel(parent=self.layoutWidget3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_9.addWidget(self.label_19, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.layoutWidget3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_9.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(parent=self.layoutWidget3)
        self.comboBox_1.setObjectName("comboBox_1")
        self.gridLayout_9.addWidget(self.comboBox_1, 0, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(parent=self.layoutWidget3)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_9.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(parent=self.layoutWidget3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(parent=self.layoutWidget3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_9)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 1, 0, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(parent=self.layoutWidget3)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_7.addWidget(self.comboBox_6, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 2, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(parent=self.layoutWidget3)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_7.addWidget(self.comboBox_4, 0, 1, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(parent=self.layoutWidget3)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_7.addWidget(self.comboBox_5, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(parent=self.layoutWidget3)
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout_5.addWidget(self.comboBox_7, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(parent=self.layoutWidget3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 1, 0, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(parent=self.layoutWidget3)
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_5.addWidget(self.comboBox_8, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.line_5 = QtWidgets.QFrame(parent=self.tab_10)
        self.line_5.setGeometry(QtCore.QRect(330, 10, 20, 341))
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.layoutWidget4 = QtWidgets.QWidget(parent=self.tab_10)
        self.layoutWidget4.setGeometry(QtCore.QRect(357, 47, 361, 281))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.comboBox_11 = QtWidgets.QComboBox(parent=self.layoutWidget4)
        self.comboBox_11.setObjectName("comboBox_11")
        self.gridLayout_10.addWidget(self.comboBox_11, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(parent=self.layoutWidget4)
        self.label_22.setObjectName("label_22")
        self.gridLayout_10.addWidget(self.label_22, 2, 0, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(parent=self.layoutWidget4)
        self.comboBox_9.setObjectName("comboBox_9")
        self.gridLayout_10.addWidget(self.comboBox_9, 0, 1, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(parent=self.layoutWidget4)
        self.comboBox_10.setObjectName("comboBox_10")
        self.gridLayout_10.addWidget(self.comboBox_10, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(parent=self.layoutWidget4)
        self.label_23.setObjectName("label_23")
        self.gridLayout_10.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(parent=self.layoutWidget4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_10.addWidget(self.label_24, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_10)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.comboBox_14 = QtWidgets.QComboBox(parent=self.layoutWidget4)
        self.comboBox_14.setObjectName("comboBox_14")
        self.gridLayout_11.addWidget(self.comboBox_14, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=self.layoutWidget4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_11.addWidget(self.label_12, 2, 0, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(parent=self.layoutWidget4)
        self.comboBox_12.setObjectName("comboBox_12")
        self.gridLayout_11.addWidget(self.comboBox_12, 0, 1, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(parent=self.layoutWidget4)
        self.comboBox_13.setObjectName("comboBox_13")
        self.gridLayout_11.addWidget(self.comboBox_13, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(parent=self.layoutWidget4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.layoutWidget4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_11)
        self.label_11 = QtWidgets.QLabel(parent=self.tab_10)
        self.label_11.setGeometry(QtCore.QRect(110, 20, 131, 16))
        self.label_11.setStyleSheet("font: 600 16pt \"Bahnschrift SemiBold\";")
        self.label_11.setObjectName("label_11")
        self.tabWidget_4.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.line_6 = QtWidgets.QFrame(parent=self.tab_11)
        self.line_6.setGeometry(QtCore.QRect(360, 20, 20, 261))
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_45 = QtWidgets.QLabel(parent=self.tab_11)
        self.label_45.setGeometry(QtCore.QRect(110, 30, 131, 16))
        self.label_45.setStyleSheet("font: 600 16pt \"Bahnschrift SemiBold\";")
        self.label_45.setObjectName("label_45")
        self.label_52 = QtWidgets.QLabel(parent=self.tab_11)
        self.label_52.setGeometry(QtCore.QRect(510, 30, 131, 16))
        self.label_52.setStyleSheet("font: 600 16pt \"Bahnschrift SemiBold\";")
        self.label_52.setObjectName("label_52")
        self.layoutWidget5 = QtWidgets.QWidget(parent=self.tab_11)
        self.layoutWidget5.setGeometry(QtCore.QRect(30, 70, 291, 146))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget5)
        self.label_6.setObjectName("label_6")
        self.gridLayout_21.addWidget(self.label_6, 0, 0, 1, 1)
        self.comboBox_m_1 = QtWidgets.QComboBox(parent=self.layoutWidget5)
        self.comboBox_m_1.setObjectName("comboBox_m_1")
        self.gridLayout_21.addWidget(self.comboBox_m_1, 0, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(parent=self.layoutWidget5)
        self.label_54.setObjectName("label_54")
        self.gridLayout_21.addWidget(self.label_54, 1, 0, 1, 1)
        self.comboBox_m_3 = QtWidgets.QComboBox(parent=self.layoutWidget5)
        self.comboBox_m_3.setObjectName("comboBox_m_3")
        self.gridLayout_21.addWidget(self.comboBox_m_3, 1, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(parent=self.layoutWidget5)
        self.label_55.setObjectName("label_55")
        self.gridLayout_21.addWidget(self.label_55, 2, 0, 1, 1)
        self.comboBox_m_4 = QtWidgets.QComboBox(parent=self.layoutWidget5)
        self.comboBox_m_4.setObjectName("comboBox_m_4")
        self.gridLayout_21.addWidget(self.comboBox_m_4, 2, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(parent=self.layoutWidget5)
        self.label_56.setObjectName("label_56")
        self.gridLayout_21.addWidget(self.label_56, 3, 0, 1, 1)
        self.comboBox_m_5 = QtWidgets.QComboBox(parent=self.layoutWidget5)
        self.comboBox_m_5.setObjectName("comboBox_m_5")
        self.gridLayout_21.addWidget(self.comboBox_m_5, 3, 1, 1, 1)
        self.layoutWidget6 = QtWidgets.QWidget(parent=self.tab_11)
        self.layoutWidget6.setGeometry(QtCore.QRect(410, 70, 291, 141))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_22.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_53 = QtWidgets.QLabel(parent=self.layoutWidget6)
        self.label_53.setObjectName("label_53")
        self.gridLayout_22.addWidget(self.label_53, 0, 0, 1, 1)
        self.comboBox_m_2 = QtWidgets.QComboBox(parent=self.layoutWidget6)
        self.comboBox_m_2.setObjectName("comboBox_m_2")
        self.gridLayout_22.addWidget(self.comboBox_m_2, 0, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(parent=self.layoutWidget6)
        self.label_57.setObjectName("label_57")
        self.gridLayout_22.addWidget(self.label_57, 1, 0, 1, 1)
        self.comboBox_m_6 = QtWidgets.QComboBox(parent=self.layoutWidget6)
        self.comboBox_m_6.setObjectName("comboBox_m_6")
        self.gridLayout_22.addWidget(self.comboBox_m_6, 1, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(parent=self.layoutWidget6)
        self.label_58.setObjectName("label_58")
        self.gridLayout_22.addWidget(self.label_58, 2, 0, 1, 1)
        self.comboBox_m_7 = QtWidgets.QComboBox(parent=self.layoutWidget6)
        self.comboBox_m_7.setObjectName("comboBox_m_7")
        self.gridLayout_22.addWidget(self.comboBox_m_7, 2, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(parent=self.layoutWidget6)
        self.label_59.setObjectName("label_59")
        self.gridLayout_22.addWidget(self.label_59, 3, 0, 1, 1)
        self.comboBox_m_8 = QtWidgets.QComboBox(parent=self.layoutWidget6)
        self.comboBox_m_8.setObjectName("comboBox_m_8")
        self.gridLayout_22.addWidget(self.comboBox_m_8, 3, 1, 1, 1)
        self.tabWidget_4.addTab(self.tab_11, "")
        self.tabWidget_3.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.layoutWidget_5 = QtWidgets.QWidget(parent=self.tab_4)
        self.layoutWidget_5.setGeometry(QtCore.QRect(70, 50, 401, 261))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_24 = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_6.addWidget(self.lineEdit_24, 0, 0, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_6.addWidget(self.lineEdit_30, 4, 0, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        self.lineEdit_40.setText("")
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_6.addWidget(self.lineEdit_40, 4, 1, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_6.addWidget(self.lineEdit_25, 0, 1, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_6.addWidget(self.lineEdit_28, 3, 0, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_6.addWidget(self.lineEdit_26, 1, 0, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_6.addWidget(self.lineEdit_29, 3, 1, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        self.lineEdit_27.setText("")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_6.addWidget(self.lineEdit_27, 1, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(parent=self.tab_4)
        self.line_4.setGeometry(QtCore.QRect(520, 30, 20, 351))
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.tab_4)
        self.pushButton_3.setGeometry(QtCore.QRect(620, 50, 471, 31))
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"border:1px solid rgb(255,0,0);\n"
"background-color:rgb(255,255,255);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:!selected\n"
"{\n"
"color:rgb(255,0,0);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color:rgb(255,0,0);\n"
"color:rgb(255,255,255)\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:!enabled\n"
"{\n"
"border:1px solid rgb(120,120,120);\n"
"background-color:rgb(255,255,255);\n"
"color:rgb(120,120,120);\n"
"border-radius:15px;\n"
"\n"
"}\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.tab_4)
        self.tableWidget_2.setGeometry(QtCore.QRect(620, 90, 471, 181))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.label_16 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(120, 20, 271, 21))
        self.label_16.setStyleSheet("font: 600 16pt \"Bahnschrift SemiBold\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(740, 20, 341, 20))
        self.label_17.setStyleSheet("font: 600 16pt \"Bahnschrift SemiBold\";")
        self.label_17.setObjectName("label_17")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.tab_4)
        self.pushButton_4.setGeometry(QtCore.QRect(620, 280, 471, 31))
        self.pushButton_4.setStyleSheet("QPushButton\n"
"{\n"
"border:1px solid rgb(255,0,0);\n"
"background-color:rgb(255,255,255);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:!selected\n"
"{\n"
"color:rgb(255,0,0);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color:rgb(255,0,0);\n"
"color:rgb(255,255,255)\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:!enabled\n"
"{\n"
"border:1px solid rgb(120,120,120);\n"
"background-color:rgb(255,255,255);\n"
"color:rgb(120,120,120);\n"
"border-radius:15px;\n"
"\n"
"}\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget_3.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_4 = QtWidgets.QLabel(parent=self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(150, 20, 49, 16))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.tab_5)
        self.pushButton_5.setGeometry(QtCore.QRect(920, 140, 251, 32))
        self.pushButton_5.setStyleSheet("QPushButton\n"
"{\n"
"height:30px;\n"
"border:1px solid rgb(255,0,0);\n"
"background-color:rgb(255,255,255);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:!selected\n"
"{\n"
"color:rgb(255,0,0);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color:rgb(255,0,0);\n"
"color:rgb(255,255,255)\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:!enabled\n"
"{\n"
"border:1px solid rgb(120,120,120);\n"
"background-color:rgb(255,255,255);\n"
"color:rgb(120,120,120);\n"
"border-radius:15px;\n"
"\n"
"}\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.tab_5)
        self.pushButton_6.setGeometry(QtCore.QRect(920, 210, 249, 32))
        self.pushButton_6.setStyleSheet("QPushButton\n"
"{\n"
"height:30px;\n"
"border:1px solid rgb(255,0,0);\n"
"background-color:rgb(255,255,255);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:!selected\n"
"{\n"
"color:rgb(255,0,0);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color:rgb(255,0,0);\n"
"color:rgb(255,255,255)\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:!enabled\n"
"{\n"
"border:1px solid rgb(120,120,120);\n"
"background-color:rgb(255,255,255);\n"
"color:rgb(120,120,120);\n"
"border-radius:15px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.MplWidget = MplWidget(parent=self.tab_5)
        self.MplWidget.setGeometry(QtCore.QRect(30, 10, 871, 400))
        self.MplWidget.setObjectName("MplWidget")
        self.tabWidget_3.addTab(self.tab_5, "")
        icon = QtGui.QIcon.fromTheme("accessories-calculator")
        self.tabWidget.addTab(self.tab_2, icon, "")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 10, 981, 31))
        self.label_5.setObjectName("label_5")
        self.label_30 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(1140, 20, 71, 16))
        self.label_30.setObjectName("label_30")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculateur d\'encrassement"))
        self.lineEdit_13.setPlaceholderText(_translate("MainWindow", "Cp sortie [Joul/Kg.C]"))
        self.lineEdit_12.setPlaceholderText(_translate("MainWindow", "Cp entré  [Joul/Kg.C]"))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "masse volumique [Kg/m^3]"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "t1 temperateur d\'entré [C"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "t2 temperateur d\'entré [C"))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "debit [m^3/h]"))
        self.lineEdit_1.setPlaceholderText(_translate("MainWindow", "T1 temperateur d\'entré [C]"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "T2 temperateur de sortie  [C]"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "debit [m^3/h]"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "masse volumique [Kg/m^3]"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Cp [Joul/Kg.C]"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "μ [Pa*s]"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "k [W/m.C]"))
        self.label_26.setText(_translate("MainWindow", "Fluide chaud"))
        self.label_27.setText(_translate("MainWindow", "Fluide froid"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.widget1), _translate("MainWindow", "Les paramètres des deux fluides"))
        self.lineEdit_16.setPlaceholderText(_translate("MainWindow", "Pression [bar]"))
        self.lineEdit_22.setPlaceholderText(_translate("MainWindow", "longeur de tube [m]"))
        self.lineEdit_23.setPlaceholderText(_translate("MainWindow", "epaisseur de tube  [m]"))
        self.lineEdit_17.setPlaceholderText(_translate("MainWindow", "Pression critique [bar]"))
        self.lineEdit_20.setPlaceholderText(_translate("MainWindow", "Nombre de passe coté calandre"))
        self.lineEdit_18.setPlaceholderText(_translate("MainWindow", "Nombre de tube"))
        self.lineEdit_21.setPlaceholderText(_translate("MainWindow", "Diamètre externe de tube [m]"))
        self.lineEdit_19.setPlaceholderText(_translate("MainWindow", "Nombre de passe coté faisceau"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Les paramètres de design"))
        self.pushButton.setText(_translate("MainWindow", "Calculer"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; font-style:italic; color:#aa0000;\">T1</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; font-style:italic; color:#aa0000;\">T2</span></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; font-style:italic; color:#0000ff;\">t1</span></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; font-style:italic; color:#0000ff;\">t2</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Calculateur simple"))
        self.pushButton_2.setText(_translate("MainWindow", "ouvrir un fichier Excel ou Csv"))
        self.radioButton_1.setText(_translate("MainWindow", "Mode 1"))
        self.radioButton_2.setText(_translate("MainWindow", "Mode 2"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; font-style:italic; text-decoration: underline;\">Mode 1 :</span></p><p><span style=\" font-size:12pt;\">Le mode 1 est un calculateur pour les fluides généraux sans correction de viscosité.</span></p><p><span style=\" font-size:12pt; font-weight:700; font-style:italic; text-decoration: underline;\">Mode 2 :</span></p><p><span style=\" font-size:12pt;\">Le mode 2 est un calculateur pour des fluides spécifiques avec correction de viscosité.</span></p></body></html>"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("MainWindow", "Choisir le mode"))
        self.label_15.setText(_translate("MainWindow", "Fluide froid"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; font-style:italic;\">T2 temperateur de sortie  [C]</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; font-style:italic;\">debit [m</span><span style=\" font-weight:700; font-style:italic; vertical-align:super;\">3</span><span style=\" font-weight:700; font-style:italic;\">/h]</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; font-style:italic;\">T1 temperateur d\'entré [C]</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; font-style:italic;\">Cp [Joul/Kg.C]</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; font-style:italic;\">μ [Pa*s]</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; font-style:italic;\">masse volumique [Kg/m</span><span style=\" font-weight:700; font-style:italic; vertical-align:super;\">3</span><span style=\" font-weight:700; font-style:italic;\">]</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; font-style:italic;\">k [W/m.C]</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; font-style:italic;\">date</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; font-style:italic;\">debit [m</span><span style=\" font-weight:700; font-style:italic; vertical-align:super;\">3</span><span style=\" font-weight:700; font-style:italic;\">/h]</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; font-style:italic;\">t2 temperateur de sortie  [C]</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; font-style:italic;\">t1 temperateur d\'entré [C]</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; font-style:italic;\">Cp liquide sortie [Joul/Kg.C] </span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; font-style:italic;\">Cp liquide  entré [Joul/Kg.C] </span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700; font-style:italic;\">masse volumique moy [Kg/m</span><span style=\" font-weight:700; font-style:italic; vertical-align:super;\">3</span><span style=\" font-weight:700; font-style:italic;\">]</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Fluide chaud"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), _translate("MainWindow", "Mode 1"))
        self.label_45.setText(_translate("MainWindow", "Fluide chaud"))
        self.label_52.setText(_translate("MainWindow", "Fluide froid"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700; font-style:italic;\">type de fluide</span></p></body></html>"))
        self.label_54.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700; font-style:italic;\">T1 temperateur d\'entré [C]</span></p></body></html>"))
        self.label_55.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700; font-style:italic;\">T2 temperateur de sortie  [C]</span></p></body></html>"))
        self.label_56.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700; font-style:italic;\">debit [m</span><span style=\" font-size:10pt; font-weight:700; font-style:italic; vertical-align:super;\">3</span><span style=\" font-size:10pt; font-weight:700; font-style:italic;\">/h]</span></p></body></html>"))
        self.label_53.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700; font-style:italic;\">type de fluide</span></p></body></html>"))
        self.label_57.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700; font-style:italic;\">t1 temperateur d\'entré [C]</span></p></body></html>"))
        self.label_58.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700; font-style:italic;\">t2 temperateur de sortie [C]</span></p></body></html>"))
        self.label_59.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700; font-style:italic;\">debit [m</span><span style=\" font-size:10pt; font-weight:700; font-style:italic; vertical-align:super;\">3</span><span style=\" font-size:10pt; font-weight:700; font-style:italic;\">/h]</span></p></body></html>"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("MainWindow", "mode 2"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab), _translate("MainWindow", "Les paramètres des deux fluides"))
        self.lineEdit_24.setPlaceholderText(_translate("MainWindow", "Pression [bar]"))
        self.lineEdit_30.setPlaceholderText(_translate("MainWindow", "longeur de tube [m]"))
        self.lineEdit_40.setPlaceholderText(_translate("MainWindow", "epaisseur de tube  [m]"))
        self.lineEdit_25.setPlaceholderText(_translate("MainWindow", "Pression critique [bar]"))
        self.lineEdit_28.setPlaceholderText(_translate("MainWindow", "Nombre de passe coté calandre"))
        self.lineEdit_26.setPlaceholderText(_translate("MainWindow", "Nombre de tube"))
        self.lineEdit_29.setPlaceholderText(_translate("MainWindow", "Diamètre externe de tube [m]"))
        self.lineEdit_27.setPlaceholderText(_translate("MainWindow", "Nombre de passe coté faisceau"))
        self.pushButton_3.setText(_translate("MainWindow", "démarrer les calculs"))
        self.label_16.setText(_translate("MainWindow", "Les paramètres de design"))
        self.label_17.setText(_translate("MainWindow", "Calculer l‘encrassement "))
        self.pushButton_4.setText(_translate("MainWindow", "sauvegarder le fichier"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), _translate("MainWindow", "Configurer le design et démarrer les calculs"))
        self.pushButton_5.setText(_translate("MainWindow", "Tracez le graphique à partir des derniers calculs."))
        self.pushButton_6.setText(_translate("MainWindow", "Tracez le graphique à partir l\'un de vous fichier."))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "Visualisation graphique des données"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Calculateur de plusieurs jours"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700; font-style:italic; text-decoration: underline;\">Calculateur d\'encrassement pour un échangeur de type Kittel avec un changement de phase du côté calandre</span></p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700; font-style:italic;\">version 0.0.1</span></p></body></html>"))
from mplwidget import MplWidget
